//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public int Id { get; set; }
        public string TraineeName { get; set; }
        public string TrainingName { get; set; }
        public bool Attendance { get; set; }
        public System.DateTime Date { get; set; }
        public int EmpId { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
