//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Attendences = new HashSet<Attendence>();
        }
    
        public int EmpId { get; set; }
        public string CertificationType { get; set; }
        public string TrainingType { get; set; }
        public string TrainingFrom { get; set; }
        public int Score { get; set; }
        public bool IsCertified { get; set; }
        public int NumberOfAttempt { get; set; }
        public int TrainingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual TrainingDetail TrainingDetail { get; set; }
    }
}
