//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingDetails()
        {
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int TrainingId { get; set; }
        public string TrainingName { get; set; }
        public string Technology { get; set; }
        public System.DateTime ExpectedStartDate { get; set; }
        public int ExpectedDurationInHours { get; set; }
        public string TotalDuration { get; set; }
        public string ExpectedEndDate { get; set; }
        public string TrainingType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
